# config/validator/validation.yaml
App\Entity\Location:
    properties:
        city:
            - NotBlank: ~
            - Length:
                min: 2
                max: 100
                groups: ['create', 'edit']
        latitude:
            - NotBlank: ~
            - Type: numeric
            - Range:
                min: -90
                max: 90
                notInRangeMessage: 'Latitude must be between {{ min }} and {{ max }}.'
                groups: ['create', 'edit']
        longitude:
            - NotBlank: ~
            - Type: numeric
            - Range:
                min: -180
                max: 180
                notInRangeMessage: 'Longitude must be between {{ min }} and {{ max }}.'
                groups: ['create', 'edit']

App\Entity\Measurement:
    properties:
        date:
            - NotBlank: ~
        celsius:
            - NotBlank: ~
            - Type: numeric
            - Range:
                min: -273.15
                max: .inf
                notInRangeMessage: 'Celsius temperature must be between {{ min }} and {{ max }}.'
                groups: ['create', 'edit']
